apiVersion: v1
kind: Service
metadata:
  name: loan-recovery-service
  namespace: default
  labels:
    app: loan-recovery-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 7860
      protocol: TCP
      name: http
  selector:
    app: loan-recovery-api
